apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github-oauth
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: argocd-github-oauth
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
      data:
        client-id: "{{ .clientId }}"
        client-secret: "{{ .clientSecret }}"
  data:
    - secretKey: clientId
      remoteRef:
        key: argocd-github-client-id
    - secretKey: clientSecret
      remoteRef:
        key: argocd-github-client-secret
