apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: gke-practice-kyosu
      auth:
        workloadIdentity:
          clusterLocation: asia-northeast1-a
          clusterName: gke-practice
          clusterProjectID: gke-practice-kyosu
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
