apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

images:
  - name: echo
    newName: asia-northeast1-docker.pkg.dev/<YOUR_PROJECT_ID>/gke-practice/echo
    newTag: latest

replicas:
  - name: echo
    count: 2
