apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

images:
  - name: echo
    newName: asia-northeast1-docker.pkg.dev/gke-practice-kyosu/gke-practice/echo
    newTag: latest

replicas:
  - name: echo
    count: 1
