apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: echo=asia-northeast1-docker.pkg.dev/gke-practice-kyosu/gke-practice/echo
    argocd-image-updater.argoproj.io/echo.update-strategy: newest-build
    argocd-image-updater.argoproj.io/echo.kustomize.image-name: echo
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-github-app
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/kyosu-1/gke-practice.git
    targetRevision: main
    path: k8s/services/echo/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
